#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'projects'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: '🔧 Blah Thingy',                       url: 'proj-blah'}
- {name: '🎮 Games',                             url: 'proj-games'}
- {name: '✨ Shaders',                           url: 'proj-shaders'}
- {name: '🐙 Squid & 🧙‍♂️ Super Karoiju Starfighter', url: 'proj-3DS'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/sublimepoulpe'}
- {icon: 'instagram', link: 'https://instagram.com/sublimepoulpe'}
- {icon: 'github',    link: 'https://github.com/takosquid'}
- {icon: 'envelope',  link: 'mailto:mailto:lepoulpequisentbon@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ""

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
